/* GD32VF103CB */
MEMORY
{
	FLASH : ORIGIN = 0x08000000, LENGTH = 128k
	RAM : ORIGIN = 0x20000000, LENGTH = 32k
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
